intergenignite/ignite

- resource/test/ignite_personas.json
> Add Personas JSON file

- resource/test/ignite_maps_map.json
Extra "Building": text in some instances
> Fixed repeated text

- resource/test/ignite_maps_map.json
Update to use the image names to load files instead of move the pointer around. The naming on this list makes more sense now.
> Updated to use images names

- resource/prod/ignite_rules.json
- resource/prod/ignite_session_map.json
Added a new SessionSetAccess called Anonymous
Updated the session set mappings so that Anonymous user won't see sessions of type Agenda
Removed unnecessary session set access for pre-days
> bug(showing Agenda Items);

- src/Ignite.Rules/Ignite.Rules/Dto/EvalaccessDto.cs
@gavinbarron I've just reflected the new data to fix the build. :camel:
> Modify evaluations dto to reflect new data & fix tests

- resource/prod/ignite_session_map.json
This will have a pre-check fail until the test branch PR is in master
> Adding new keynotes to prod session map file

- resource/prod/ignite_session_map.json
https://www.yammer.com/microsofteventsteam/#/files/64261868
> Adding idls to session catalog in prod

- resource/test/ignite_session_map.json
as per https://www.yammer.com/microsofteventsteam/#/files/64261868
> Adding IDLs to mktg site (to TEST)

- src/Ignite.Rules/Ignite.Rules.Test/PermissionManagerTest.cs
Not 100% sure this is rules file valid but it will make the tests pass!
> Adding schedule builder attendee permissions to the friday list

- resource/test/ignite_news.json
- resource/test/ignite_personas.json
Includes:
- Titles
- Links to 2017 images
- Sample links and descriptions
> News changes for 2017

- resource/prod2017/ignite_learning_paths.json
- resource/prod2017/ignite_personas.json
- resource/test/ignite_learning_paths.json
- resource/test/ignite_personas.json
- Add new learning path resource
- Extend personas to include example sidebar content
> Learning path overhaul

- resource/prod2017/ignite_news.json
Haven't tested this yet - azure portal giving me issues - working on it now.
> Updates post show

- resource/prod2017/ignite_news.json
Uploaded a modified and renamed image file for evaluations.  Can either wait for CDN to expire the cached image (which I've also uploaded a new file for) or merge this which points to the new image.
> Update to image size

- resource/inspire2018/rules.json
- resource/inspire2018/session_map.json
Cleaning up session catalog idenitfier
> Cleaning up session catalog identifier

- resource/ignite2018/ignite_session_map.json
Including agenda and MVP pre-day which are schedule only, not in the session catalog
> Add extra session types

- resource/ignite2018/profileMetadataDetails.json
update to the profile metadata.... including optins and removing items that are no longer shown
> Update to the profile metadata

- resource/ignite2018/profileMetadataDetails.json
Updating details for the profile
> Updating profile details 

- resource/ignite2018/sidebarMetadata.json
Adding PPT and video download links to video and session
> Add PPT and video download links to video and

- resource/build2019-test/rules.json
Update session detail page sidebar details for Build.
> Update session detail page sidebar details for Build

- resource/inspire2019-prod/sidebarMetadata.json
@gavinbarron there is a bit more in here than just the Product filter update, please review and ensure that you want all of these updates :)
> Copy sidebar metadata rules from test

- resource/inspire2019-prod/rules.json
- resource/inspire2019-test/rules.json
added myschedule access to inspire2019 rules - Allows agenda items to be searched in index
> added myschedule access to inspire2019 rules

- resource/inspire2019-prod/profileMetadataDetails.json
- resource/inspire2019-prod/sidebarMetadata.json
- resource/inspire2019-test/sidebarMetadata.json
- Update sidebarMetaData to include session trailer link
- Also bring over other changes in from inspire2019-test "profileMetadataDetails.json" and "sidebarMetadata.json" into inspire2019-PROD
> Update sidebarMetaData to include session trailer link

- resource/ignite2019-test/sidebarMetadata.json
Updated only session section of sidebarMetadata.json
> Update ignite2019-test sidebar for sessions

- resource/ignite2019-test/sidebarMetadata.json
Change session learning path and product to leafNodeFilters
> Change product and learning path on session to leafnodefilters

- resource/ignite2019-prod/session_map.json
- resource/ignite2019-test/session_map.json
Updating ignite 2019 session mapping as per updates to AzureDevOps Card https://intergen.visualstudio.com/Intergen.EventTools.Platform/_workitems/edit/63626
> update ignite2019 sessionmaps

- resource/ignite2019-prod/profileMetadataDetails.json
- resource/ignite2019-prod/rules.json
- resource/ignite2019-prod/session_map.json
- resource/ignite2019-test/profileMetadataDetails.json
- resource/ignite2019-test/rules.json
- resource/ignite2019-test/session_map.json
- resource/mitt2019-prod/session_map.json
- resource/mitt2019-test/session_map.json
Update session types for ignite2019
Added
- openhack
- agenda
- leadership forum
> Update session types for ignite2019

- resource/ignite2019-prod/profileMetadataDetails.json
- resource/ignite2019-test/profileMetadataDetails.json
- resource/mitt2019-prod/session_map.json
- resource/mitt2019-test/session_map.json
Update ignite2019 recommendation fields on profile
Remove unused opt-ins
> Update ignite2019 recommendation fields on profile & removed unused opt-ins

- resource/ignite2019-prod/profileMetadataDetails.json
- resource/ignite2019-test/profileMetadataDetails.json
removed social links from profile, restore optins
> removed social links from profile, restore optins
